# Generated by Django 3.0.8 on 2021-09-05 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportDate_year', models.CharField(max_length=4, verbose_name='報告年')),
                ('ReportDate_month', models.CharField(max_length=2, verbose_name='報告月')),
            ],
        ),
        migrations.CreateModel(
            name='FoundItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoundItems_Year', models.CharField(max_length=4, verbose_name='報告年')),
                ('FoundItems_Month', models.CharField(max_length=4, verbose_name='報告月')),
                ('files', models.FileField(blank=True, upload_to='item/%Y/')),
                ('create_user', models.CharField(blank=True, max_length=20, verbose_name='報告者名')),
                ('create_date', models.DateField()),
                ('memo', models.TextField(blank=True, default=None, verbose_name='コメント')),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ホテル名')),
            ],
        ),
    ]
