# Generated by Django 3.0.8 on 2021-09-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='memo',
            field=models.TextField(blank=True, default=None, max_length=100, verbose_name='コメント'),
        ),
    ]
