# Generated by Django 3.0.8 on 2021-10-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='カテゴリー')),
                ('c_order', models.IntegerField(unique=True, verbose_name='表示順')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_rank', models.CharField(max_length=10, verbose_name='ランク名')),
                ('cr_order', models.IntegerField(unique=True, verbose_name='表示順')),
                ('cr_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.Category', verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('p_order', models.IntegerField(unique=True, verbose_name='表示順')),
                ('p_body', models.TextField(verbose_name='本文')),
                ('p_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual.CategoryRank', verbose_name='カテゴリー')),
            ],
        ),
    ]
