# Generated by Django 3.0.8 on 2021-10-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrank',
            name='cr_order',
            field=models.IntegerField(verbose_name='表示順'),
        ),
    ]
