# Generated by Django 3.0.8 on 2021-10-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_auto_20211003_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p_order',
            field=models.IntegerField(verbose_name='表示順'),
        ),
    ]
